[package]
name = "iso-rs"
version = "0.2.0"
authors = ["Daksh14 <41485688+Daksh14@users.noreply.github.com>"]
edition = "2024"
build = "build/build.rs"
description = "A crate to query ISO data, which includes countries, currencies, etc."
license = "MIT"
repository = "https://github.com/dashxhq/iso-rs"
readme = "README.md"
keywords = ["iso", "country", "currency", "iso3166", "timezone"]
categories = ["internationalization", "data-structures"]
rust-version = "1.85"
exclude = ["AGENTS.md", "CLAUDE.md", ".github/", "scripts/"]

[dependencies]
chrono-tz = "0.10"
phf = "0.14"

[build-dependencies]
phf_codegen = "0.14"
proc-macro2 = "1.0"
quote = "1.0"
serde_json = "1"

[features]
default = ["all"]
from_capitals = []
from_alpha_2 = []
from_alpha_3 = []
from_regions = []
from_subregions = []
all = [
    "from_capitals",
    "from_alpha_2",
    "from_alpha_3",
    "from_regions",
    "from_subregions",
]
